version: '3.8'

services:
  taskflow-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: taskflow-api
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://quarkus_postgres:5432/system_vacation_db
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus123
      QUARKUS_PROFILE: dev  # ← MUDE PARA 'dev' TEMPORARIAMENTE
      QUARKUS_FLYWAY_CLEAN_AT_START: "true"  # ← FORÇA LIMPEZA
    ports:
      - "127.0.0.1:8083:8080"
    # - "8083:8083" # Se quiser expor para toda a rede local, mas bloqueado para impedir acesso externo
    # Conecta este container à rede que já existe
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true